version: "3.8"

services:

  postgres:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: unless-stopped

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - migrations
      - redis
    restart: unless-stopped

  migrations:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",
               "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}", "up" ]
    depends_on:
      - postgres
    restart: on-failure

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pg-data:
  redis-data: